import pandas as pd

index_etf = []
sector_etf = []
nasdaq_100 = ["AAPL",
              "MSFT",
              "GOOG",
              "GOOGL",
              "AMZN",
              "TSLA",
              "META",
              "NVDA",
              "PEP",
              "COST",
              "ASML",
              "AVGO",
              "AZN",
              "CMCSA",
              "CSCO",
              "ADBE",
              "QCOM",
              "TMUS",
              "INTC",
              "TXN",
              "AMD",
              "AMGN",
              "HON",
              "INTU",
              "JD",
              "CHTR",
              "NFLX",
              "PYPL",
              "SBUX",
              "ADP",
              "AMAT",
              "MDLZ",
              "ADI",
              "ISRG",
              "GILD",
              "BKNG",
              "VRTX",
              "PDD",
              "CSX",
              "MU",
              "MRNA",
              "REGN",
              "NTES",
              "LRCX",
              "FISV",
              "ABNB",
              "ATVI",
              "KDP",
              "SNPS",
              "MNST",
              "PANW",
              "MAR",
              "KLAC",
              "TEAM",
              "AEP",
              "BIDU",
              "FTNT",
              "KHC",
              "CDNS",
              "NXPI",
              "ORLY",
              "PAYX",
              "EXC",
              "MRVL",
              "ADSK",
              "CRWD",
              "CTAS",
              "LULU",
              "MELI",
              "XEL",
              "DLTR",
              "WDAY",
              "EA",
              "MCHP",
              "CTSH",
              "WBA",
              "DXCM",
              "SGEN",
              "ZM",
              "IDXX",
              "ILMN",
              "LCID",
              "ODFL",
              "BIIB",
              "PCAR",
              "ROST",
              "VRSK",
              "CPRT",
              "DDOG",
              "FAST",
              "EBAY",
              "SIRI",
              "ANSS",
              "ZS",
              "MTCH",
              "VRSN",
              "ALGN",
              #"CEG",
              "SWKS",
              "SPLK",
              "OKTA",
              "DOCU"]

market_caps = ["All", "Mega cap", "Large cap", "Mid cap"]

sectors = ["All",
           "Materials",
           "Consumer Dis",
           "Consumer Stap",
           "Health Care",
           "Industrials",
           "Tech",
           "Telecom",
           "Utilities"]

tickerPriceInfo = {}

def readAllPriceCsv():
    for ticker in nasdaq_100:
        df = pd.read_csv('Resources/NASDQ-100-Tickers/' + ticker + '.csv')
        tickerPriceInfo[ticker] = df
